# Den usikre, interne dør (Port 1883) - Bruges af ChirpStack internt
listener 1883 0.0.0.0
listener_allow_anonymous true

# Den topsikrede dør udefra (Port 8883 TLS)
listener 8883 0.0.0.0
cafile /mosquitto/certs/ca.pem
certfile /mosquitto/certs/mqtt-server.pem
keyfile /mosquitto/certs/mqtt-server-key.pem
listener_allow_anonymous true
require_certificate false
tls_version tlsv1.2

# mTLS listener for Application Server MQTT listener test
listener 8884 0.0.0.0
cafile /mosquitto/certs/ca.pem
certfile /mosquitto/certs/mqtt-server.pem
keyfile /mosquitto/certs/mqtt-server-key.pem
require_certificate true
use_identity_as_username true
listener_allow_anonymous false
