listener 8884 0.0.0.0
cafile /mosquitto/certs/ca.pem
certfile /mosquitto/certs/mqtt-server.pem
keyfile /mosquitto/certs/mqtt-server-key.pem
require_certificate true
use_identity_as_username true
listener_allow_anonymous false
